### PR TITLE
3.12.3

### PR DESCRIPTION
**Pull request by etienne-martin**

### CODE REVIEW

**Comment by whimsicaldreamer** [comment]
Alright I ran tests locally, and only 4 tests fail now rather than 8 before. Significant Improvement!! 👍 
The issue is with the Ordissimo brand which makes the tests fail.

**Comment by etienne-martin** [comment]
> How many tests failing now?

You can see how many tests are failing in circleci by clicking on "Details" 

image

**Comment by etienne-martin** [comment]
Good job and thanks for your contribution 🙏

**Comment by etienne-martin** [comment]
I will release a new version on npm

**Comment by whimsicaldreamer** [comment]
That's great!! Btw readme needs an update to reference that this library is at par with the original library version.

**Comment by etienne-martin** [comment]
You're right! I will make the change right away

**Comment by whimsicaldreamer** [comment]
Alrighty then! We are set for a new release!! 🎉

**Comment by etienne-martin** [comment]
You can follow the release stages here: https://circleci.com/workflow-run/2afeac4d-c0a2-4be7-9563-4e269c0c9c82

**Comment by etienne-martin** [comment]
Alright, it's live

**Comment by whimsicaldreamer** [comment]
Great!! 😀😀

**Comment by whimsicaldreamer** [comment]
@etienne-martin We are missing a release tag here on github.

**Pull request merged**
