### PR TITLE
Updating to 6.0.2

### PR DESCRIPTION
**Pull request by whimsicaldreamer**

### CODE REVIEW

**Comment by whimsicaldreamer** [comment]
@etienne-martin I would like to know how you would want to approach the parser issue.

**Comment by etienne-martin** [comment]
@whimsicaldreamer The gap between version 4.2.3 and version 6 is [quite big](https://github.com/matomo-org/device-detector/compare/4.2.3...6.0.3) with more than 700 commits and 164 files changed. I think it would be much easier to upgrade [from version 4 to version 5](https://github.com/matomo-org/device-detector/compare/4.2.3...5.0.5) before tackling version 6. Otherwise we might be taking too big of a bite.

**Comment by etienne-martin** [comment]
@coreymaroney if you can help with migrating to version 5 first it'd be awesome ☝️

**Comment by coreymaroney** [comment]
@etienne-martin I'll look into it ASAP. Thank you for the prompt replies!

**Pull request closed without merging**
